In [26]:
import pandas as pd

In [27]:
from matplotlib import pyplot as plt
%matplotlib inline

In [28]:
df = pd.read_csv("Iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [29]:
df.sample

<bound method NDFrame.sample of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]>

In [30]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [31]:
df = df.drop("Id", axis='columns')

In [32]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [33]:
X = df.drop('Species', axis= 'columns')

In [34]:
X

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [36]:
y = df.Species

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.3)

In [42]:
X_train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
105            7.6           3.0            6.6           2.1
29             4.7           3.2            1.6           0.2
61             5.9           3.0            4.2           1.5
40             5.0           3.5            1.3           0.3
102            7.1           3.0            5.9           2.1
103            6.3           2.9            5.6           1.8
94             5.6           2.7            4.2           1.3
15             5.7           4.4            1.5           0.4
70             5.9           3.2            4.8           1.8
23             5.1           3.3            1.7           0.5
64             5.6           2.9            3.6           1.3
52             6.9           3.1            4.9           1.5
114            5.8           2.8            5.1           2.4
25             5.0           3.0            1.6           0.2
147            6.5           3.0            5.2           2.0
132            6.4           2.8            5.6           2.2
74             6.4           2.9            4.3           1.3
130            7.4           2.8            6.1           1.9
138            6.0           3.0            4.8           1.8
42             4.4           3.2            1.3           0.2
91             6.1           3.0            4.6           1.4
4              5.0           3.6            1.4           0.2
101            5.8           2.7            5.1           1.9
71             6.1           2.8            4.0           1.3
24             4.8           3.4            1.9           0.2
18             5.7           3.8            1.7           0.3
67             5.8           2.7            4.1           1.0
118            7.7           2.6            6.9           2.3
82             5.8           2.7            3.9           1.2
135            7.7           3.0            6.1           2.3
84             5.4           3.0            4.5           1.5
69             5.6           2.5            3.9           1.1
126            6.2           2.8            4.8           1.8
34             4.9           3.1            1.5           0.1
112            6.8           3.0            5.5           2.1
85             6.0           3.4            4.5           1.6
98             5.1           2.5            3.0           1.1
26             5.0           3.4            1.6           0.4
31             5.4           3.4            1.5           0.4
83             6.0           2.7            5.1           1.6
62             6.0           2.2            4.0           1.0
109            7.2           3.6            6.1           2.5
36             5.5           3.5            1.3           0.2
78             6.0           2.9            4.5           1.5
117            7.7           3.8            6.7           2.2

In [43]:
X_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
110            6.5           3.2            5.1           2.0
108            6.7           2.5            5.8           1.8
21             5.1           3.7            1.5           0.4
104            6.5           3.0            5.8           2.2
10             5.4           3.7            1.5           0.2
..             ...           ...            ...           ...
8              4.4           2.9            1.4           0.2
6              4.6           3.4            1.4           0.3
72             6.3           2.5            4.9           1.5
99             5.7           2.8            4.1           1.3
133            6.3           2.8            5.1           1.5

[105 rows x 4 columns]

In [44]:
y_train

105     Iris-virginica
29         Iris-setosa
61     Iris-versicolor
40         Iris-setosa
102     Iris-virginica
103     Iris-virginica
94     Iris-versicolor
15         Iris-setosa
70     Iris-versicolor
23         Iris-setosa
64     Iris-versicolor
52     Iris-versicolor
114     Iris-virginica
25         Iris-setosa
147     Iris-virginica
132     Iris-virginica
74     Iris-versicolor
130     Iris-virginica
138     Iris-virginica
42         Iris-setosa
91     Iris-versicolor
4          Iris-setosa
101     Iris-virginica
71     Iris-versicolor
24         Iris-setosa
18         Iris-setosa
67     Iris-versicolor
118     Iris-virginica
82     Iris-versicolor
135     Iris-virginica
84     Iris-versicolor
69     Iris-versicolor
126     Iris-virginica
34         Iris-setosa
112     Iris-virginica
85     Iris-versicolor
98     Iris-versicolor
26         Iris-setosa
31         Iris-setosa
83     Iris-versicolor
62     Iris-versicolor
109     Iris-virginica
36         Iris-setosa
78     Iris-versicolor
117     Iris-virginica
Name: Species, dtype: object

In [45]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [51]:
model.fit(X_test,y_test)

LogisticRegression()

In [52]:
model.score(X_test,y_test)

0.9904761904761905

In [53]:
model.predict([[6.6, 3.0, 6.6, 21]])

D:\Anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array(['Iris-virginica'], dtype=object)

In [54]:
model.predict([[5.1, 3.5, 1.4, 0.2]])

D:\Anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array(['Iris-setosa'], dtype=object)